[versions]
about-libraries = "11.1.4"
android-gradle-plugin = "8.4.1"
android-secrets-plugin = "2.0.1"
androidx-lifecycle = "2.7.0"
androidx-media3 = "1.3.1"
androidx-navigation = "2.7.7"
androidx-paging = "3.3.0"
androidx-room = "2.6.1"
androidx-test-ext-junit = "1.1.5"
androidx-work = "2.9.0"
baselineprofile = "1.2.4"
benchmark-macro-junit4 = "1.2.4"
coil = "2.6.0"
detekt = "1.23.6"
espresso-core = "3.5.1"
espresso-intents = "3.5.1"
glean = "54.0.0"
google-truth = "1.4.2"
junit = "4.13.2"
koin = "3.5.6"
koin-compose = "1.1.5"
kotlin = "2.0.0"
kotlin-ksp = "2.0.0-1.0.21" # Used only once, but keeping this definition makes the KSP version check at ci/verify-ksp-version.sh simpler.
kotlinx-coroutines = "1.8.1"
ktor = "2.3.11"
okhttp = "4.12.0"
profileinstaller = "1.3.1"
protobuf = "4.26.1"
uiautomator = "2.3.0"

[libraries]
about-libraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "about-libraries" }
about-libraries-ui = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "about-libraries" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.9.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
androidx-browser = { module = "androidx.browser:browser", version = "1.8.0" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2024.05.00" }
androidx-compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-windowClass = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing", version = "1.0.0-beta01" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.0.1" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-datastore = { module = "androidx.datastore:datastore", version = "1.1.1" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso-intents" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "androidx-media3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation"}
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "androidx-navigation" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-room = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "androidx-work" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
glean = { module = "org.mozilla.telemetry:glean", version.ref = "glean" }
glean-forUnitTests = { module = "org.mozilla.telemetry:glean-native-forUnitTests", version.ref = "glean" }
google-truth = { module = "com.google.truth:truth", version.ref = "google-truth" }
google-material = { module = "com.google.android.material:material", version = "1.12.0" }
jakewharton-timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.6.0" }
kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version = "1.0.0" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.3" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
mockk = { module = "io.mockk:mockk", version = "1.13.11" }
mozilla-components-service-glean = { module = "org.mozilla.components:service-glean", version = "118.0" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version = "2.11.0" }
square-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
square-okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
unifiedPush-androidConnector = { module = "com.github.UnifiedPush:android-connector", version = "2.4.0" }

# Dependencies of build-logic
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
android-secrets-gradlePlugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "android-secrets-plugin" }
detekt-gradlePlugin = { module = "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin", version.ref = "detekt" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
about-libraries-plugin = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "about-libraries" }
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
android-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "android-secrets-plugin" }
android-test = { id = "com.android.test", version.ref = "android-gradle-plugin" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
glean = { id = "org.mozilla.telemetry.glean-gradle-plugin", version.ref = "glean" }
jetbrains-python = { id = "com.jetbrains.python.envs", version = "0.0.31" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
protobuf = { id = "com.google.protobuf", version = "0.9.4" }
sentry = { id = "io.sentry.android.gradle", version = "4.6.0" }
